<a href="https://colab.research.google.com/github/mbuitragoc/MetNumUN2023I/blob/main/Lab8/diy_lu_Optimized.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def diy_lu_column_pivot_reconstruct(A):
    """Construct the LU decomposition of the input matrix.
    
    LU decomposition with pivot: work column by column, accumulate elementary triangular matrices L @ np.transpose(Pj) .
    """
    N = A.shape[0]
    
    U = A.copy()
    L = np.eye(N)
    P = np.eye(N) #permutation matrix

    for j in range(N-1):
        
        
        #find row of max value in col j and swap that with row j
        row = np.argmax(np.abs(U[j:,j]))+j #get row with max
        #swap rows in matrix u with permutation matrix
        U[[j,row]] = U[[row,j]] #swap the rows
        
        #Update  the permutation matrix
        Pj = np.eye(N)
        Pj[[j,row]] = Pj[[row,j]]
        
        Lj = np.eye(N)
        gamma = U[j+1:, j] / U[j, j]
        Lj[j+1:, j] = -gamma
        U = Lj @ U

        Lj[j+1:, j] = gamma  #  inv(Lj) = - Lj
        
        P =  Pj @P 
        
        L = L @ Pj @ Lj


    L =  P@L
    return  P,L,U

In [16]:
import numpy as np
def diy_lu_optimized(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)
    P = np.eye(n)

    for k in range(n - 1):
        pivote = np.argmax(np.abs(U[k:, k])) + k
        if pivote != k:
            U[[k, pivote], :] = U[[pivote, k], :]
            P[[k, pivote], :] = P[[pivote, k], :]
            if k >= 1:
                L[[k, pivote], :k] = L[[pivote, k], :k]

        for i in range(k + 1, n):
            L[i, k] = U[i, k] / U[k, k]
            U[i, k:] -= L[i, k] * U[k, k:]

    return P, L, U

In [19]:
def reconstruct_matrix(P, L, U):
    return P.T @ L @ U

In [20]:
a = np.array([[2, 1, 1], [4, 3, 3], [8, 7, 9]], dtype=np.float64)
P, L, U = diy_lu_optimized(a)
reconstructed_a = reconstruct_matrix(P, L, U)

print("Original a:")
print(a)
print("Reconstruccion:")
print(reconstructed_a)
print("Igualdad:", (np.allclose(a, reconstructed_a)))

Original a:
[[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]]
Reconstruccion:
[[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]]
Igualdad: True


In [3]:
import time

import numpy as np

N = 500
A = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        A[i, j] = 3. / (0.6*i*j + 1)

np.linalg.matrix_rank(A)

10

In [4]:
tic2 = time.perf_counter()
diy_lu_optimized(A)
toc2 = time.perf_counter()
print(f"Time in {toc2 - tic2:0.4f} seconds")

Time in 0.4577 seconds


In [5]:
tic = time.perf_counter()
diy_lu_column_pivot_reconstruct(A)
toc = time.perf_counter()

print(f"Time in {toc - tic:0.4f} seconds")


Time in 13.9538 seconds


In [ ]:
N = 800
A = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        A[i, j] = 3. / (0.6*i*j + 1)

np.linalg.matrix_rank(A)

10

In [ ]:
tic2 = time.perf_counter()
diy_lu_optimized(A)
toc2 = time.perf_counter()
print(f"Time in {toc2 - tic2:0.4f} seconds")

Time in 0.3216 seconds


In [ ]:
tic = time.perf_counter()
diy_lu_column_pivot_reconstruct(A)
toc = time.perf_counter()

print(f"Time in {toc - tic:0.4f} seconds")


Time in 81.4029 seconds


In [ ]:
N = 1000
A = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        A[i, j] = 3. / (0.6*i*j + 1)

np.linalg.matrix_rank(A)

10

In [ ]:
tic2 = time.perf_counter()
diy_lu_optimized(A)
toc2 = time.perf_counter()
print(f"Time in {toc2 - tic2:0.4f} seconds")

Time in 0.5481 seconds


In [ ]:
tic = time.perf_counter()
diy_lu_column_pivot_reconstruct(A)
toc = time.perf_counter()

print(f"Time in {toc - tic:0.4f} seconds")

Time in 194.5315 seconds
